version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_biblioteca_v1
      - DB_USER=root
      - DB_PASSWORD=root
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql_biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_biblioteca_v1
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always